version: "3.3"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "yarn && yarn start"
    environment:
      NODE_ENV: development
      #Api rede globo
      API_GLOBO: https://epg-api.video.globo.com/programmes/1337

     
